basic of numpy

In [1]:
import numpy as np

list vs array

In [2]:
py_list = [1,2,3]
print("pyhon list multiplication",py_list * 2)

pyhon list multiplication [1, 2, 3, 1, 2, 3]


In [4]:
np_array =np.array ([1,2,3]) #element wise multiplication
print("pyhon array multiplication",np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n list operation time ",time.time()-start)

start = time.time()
np_array = np.arange(10000000)
print("\n numpy array operation time ",time.time()-start)

pyhon array multiplication [2 4 6]

 list operation time  0.6703338623046875

 numpy array operation time  0.023604154586791992


Creating Array From Scratch

In [14]:
zeros = np.zeros((3,4))
print("zeros array:\n",zeros)

ones = np.ones((3,4))
print("ones array:\n",ones)

full = np.full((3,4),5)
print("full array:\n",full)

random = np.random.random((3,4))
print("random array:\n",random * 100)
sequence = np.arange(0,10,2)
print("sequence array:\n",sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array:
 [[35.87462888 80.94388905  5.81792229 27.79309908]
 [25.3924372  29.51186534 66.26868901 10.04164796]
 [86.74788616 71.17075151 24.18375165 82.30828837]]
sequence array:
 [0 2 4 6 8]


vector matrix and tensor

In [17]:
vector = np.array([1,2,3,4])
print("vector:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix :\n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor :\n",tensor)


vector: [1 2 3 4]
matrix :
 [[1 2 3]
 [4 5 6]]
tensor :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [21]:
arr = np.array([[1,2,3],[4,5,6]])
print("array is:\n",arr)
print("shape:",arr.shape)
print("dimension:",arr.ndim)
print("size:",arr.size)
print("data type:",arr.dtype)

array is:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2
size: 6
data type: int64


Array reshaping

In [34]:
arr = np.arange(12)
print("original array:\n",arr)

reshaped = arr.reshape((3,4))
print("reshaped array:\n",reshaped)

flattened = reshaped.flatten()
print("flattened array:\n",flattened)

# return view, intead of copy(original array)
raveled = reshaped.ravel()
print("raveled array:\n",raveled)

#transpose
transpose = reshaped.T
print("transpose array:\n",transpose)



original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
